import { Activity } from "./types";

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "1",
    type: "online_class",
    title: "Introduction to Neural Networks",
    course: "Machine Learning",
    instructor: "Dr. Sarah Chen",
    startTime: "2025-12-24T10:00:00",
    duration: "90 min",
    meetingLink: "https://zoom.us/j/123",
    status: "upcoming",
  },
  {
    id: "2",
    type: "assignment",
    title: "Build a CNN Image Classifier",
    course: "Machine Learning",
    dueDate: "2025-12-26T23:59:00",
    points: 100,
    submissionStatus: "not_started",
    status: "upcoming",
  },
  {
    id: "3",
    type: "quiz",
    title: "AWS Services Overview",
    course: "Cloud Computing",
    dueDate: "2025-12-25T18:00:00",
    points: 50,
    duration: "30 min",
    submissionStatus: "not_started",
    status: "upcoming",
  },
  {
    id: "4",
    type: "discussion",
    title: "Ethics in AI Development",
    course: "AI Fundamentals",
    dueDate: "2025-12-27T23:59:00",
    posts: 12,
    requiredPosts: 2,
    submissionStatus: "in_progress",
    status: "in_progress",
  },
  {
    id: "5",
    type: "online_class",
    title: "Deep Dive into Transformers",
    course: "AI Fundamentals",
    instructor: "Prof. Michael Torres",
    startTime: "2025-12-23T14:00:00",
    duration: "120 min",
    meetingLink: "https://zoom.us/j/456",
    status: "completed",
  },
  {
    id: "6",
    type: "assignment",
    title: "Deploy Microservices on Kubernetes",
    course: "Cloud Computing",
    dueDate: "2025-12-22T23:59:00",
    points: 150,
    submissionStatus: "submitted",
    status: "overdue",
  },
];
